"""The debate arms produce stored rows, and produce them the way the control does.

This is the claim :mod:`council.agents.runner` makes about the debate layer and the
one :mod:`council.agents.inference` was given peer arguments for: a debate round is
generated by the same function as an independent decision, so the failure handling,
the peer fencing and the provenance hash are not reimplemented for the treatment
arms alone. A second code path would differ from the control by more than the
manipulation, and nothing in a stored row would say so.
"""

from __future__ import annotations

from datetime import UTC, datetime

from council.agents.mock import MockProvider
from council.agents.prompt import build_prompt
from council.agents.provider import Provider, ProviderUnavailableError
from council.debate.caller import DecisionCaller
from council.debate.protocol import run_debate
from council.domain.persona import PERSONAS
from council.domain.signal import Arm, FailureMode
from helpers_debate import DAY, MODELS, PRICE_CONTEXT, TICKER, committee, contested

SEED = 20260101

FROZEN = datetime(2026, 1, 1, tzinfo=UTC)


def _clock() -> datetime:
    return FROZEN


def _providers(**overrides: Provider) -> dict[str, Provider]:
    return {model: overrides.get(model, MockProvider(model=model)) for model in MODELS}


def _caller(**overrides: Provider) -> DecisionCaller:
    return DecisionCaller(
        providers=_providers(**overrides),
        composition=committee(),
        ticker=TICKER,
        decision_date=DAY,
        seed=SEED,
        clock=_clock,
    )


async def test_a_debate_writes_two_rows_per_seat_in_the_arm_it_was_run_under() -> None:
    # Arrange
    caller = _caller()

    # Act
    await run_debate(
        composition=committee(),
        arm=Arm.DEBATE,
        dispersion=contested(),
        price_context=PRICE_CONTEXT,
        caller=caller,
        seed=SEED,
    )

    # Assert
    rows = [generated.decision for generated in caller.generated]
    assert len(rows) == 8
    assert {row.arm for row in rows} == {Arm.DEBATE}
    assert sorted(row.round_index for row in rows) == [0] * 4 + [1] * 4
    assert {row.composition for row in rows} == {"rotation-0"}
    assert {(row.decision_date, row.ticker) for row in rows} == {(DAY, TICKER)}


async def test_the_opening_rows_carry_the_control_prompts_hash() -> None:
    # Arrange -- the debate's round 0 is the independent question, so it is the
    # same text and therefore the same digest. A different hash here would mean the
    # committee had been asked something the control was not.
    caller = _caller()

    # Act
    await run_debate(
        composition=committee(),
        arm=Arm.DEBATE,
        dispersion=contested(),
        price_context=PRICE_CONTEXT,
        caller=caller,
        seed=SEED,
    )

    # Assert
    control = {
        persona.name: build_prompt(persona=persona, price_context=PRICE_CONTEXT).prompt_hash
        for persona in PERSONAS
    }
    openings = [row.decision for row in caller.generated if row.decision.round_index == 0]
    for row in openings:
        assert row.prompt_hash == control[row.persona]


async def test_a_rebuttal_row_records_the_peer_block_it_was_answering() -> None:
    # Arrange
    caller = _caller()

    # Act
    transcript = await run_debate(
        composition=committee(),
        arm=Arm.DEBATE,
        dispersion=contested(),
        price_context=PRICE_CONTEXT,
        caller=caller,
        seed=SEED,
    )

    # Assert -- the archive line holds the full user turn, peer block included, so
    # the anonymisation can be audited from disk without regenerating anything.
    records = {
        (record.record.model, record.record.round_index): record.record
        for record in caller.generated
    }
    for turn in transcript.final:
        archived = records[(turn.seat.model, 1)]
        assert archived.user == turn.user
        assert archived.prompt_hash == turn.prompt.prompt_hash
        for peer in turn.peers:
            assert peer.label in archived.user


async def test_a_model_that_never_answers_still_produces_rows_and_shows_no_peer() -> None:
    # Arrange -- a decision point always produces a row, and a flat placeholder must
    # not reach the peer block as an analyst arguing for no position at all.
    unreachable = MockProvider(
        model="beta", responses=[ProviderUnavailableError("the daemon is down")]
    )
    caller = _caller(beta=unreachable)

    # Act
    transcript = await run_debate(
        composition=committee(),
        arm=Arm.DEBATE,
        dispersion=contested(),
        price_context=PRICE_CONTEXT,
        caller=caller,
        seed=SEED,
    )

    # Assert
    failed = [row.decision for row in caller.generated if row.decision.model == "beta"]
    assert len(failed) == 2
    assert {row.failure for row in failed} == {FailureMode.UNAVAILABLE}
    for turn in transcript.final:
        expected = 3 if turn.seat.model == "beta" else 2
        assert len(turn.peers) == expected
